"""create users table

Revision ID: b871398ed95d
Revises: 
Create Date: 2024-11-04 11:41:32.539455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b871398ed95d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
    op.drop_column('users', 'family_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
