// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7x0KVJqg3OQ-Yn-0oDQamD8PL1LIZjDY',
    appId: '1:123798050184:web:c61dc90fa2c2091828163d',
    messagingSenderId: '123798050184',
    projectId: 'mealplanner-86fce',
    authDomain: 'mealplanner-86fce.firebaseapp.com',
    databaseURL: 'https://mealplanner-86fce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealplanner-86fce.appspot.com',
    measurementId: 'G-12V83KZSE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrrSt4hOef5FOv2F95McussAN4Kt8tpd0',
    appId: '1:123798050184:android:f5ee1153ac7d726628163d',
    messagingSenderId: '123798050184',
    projectId: 'mealplanner-86fce',
    databaseURL: 'https://mealplanner-86fce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealplanner-86fce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBukYGfW4p14Bfud0rV9YfUe3fQazrKJ-A',
    appId: '1:123798050184:ios:f819592c0cf92afd28163d',
    messagingSenderId: '123798050184',
    projectId: 'mealplanner-86fce',
    databaseURL: 'https://mealplanner-86fce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealplanner-86fce.appspot.com',
    androidClientId: '123798050184-jviv84iov1mdhrkvmh1isan42klfv59i.apps.googleusercontent.com',
    iosClientId: '123798050184-rodoqesuc9slqiegvtrldtcjubkve1ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBukYGfW4p14Bfud0rV9YfUe3fQazrKJ-A',
    appId: '1:123798050184:ios:f819592c0cf92afd28163d',
    messagingSenderId: '123798050184',
    projectId: 'mealplanner-86fce',
    databaseURL: 'https://mealplanner-86fce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealplanner-86fce.appspot.com',
    androidClientId: '123798050184-jviv84iov1mdhrkvmh1isan42klfv59i.apps.googleusercontent.com',
    iosClientId: '123798050184-rodoqesuc9slqiegvtrldtcjubkve1ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7x0KVJqg3OQ-Yn-0oDQamD8PL1LIZjDY',
    appId: '1:123798050184:web:defb8a926e3c5f6a28163d',
    messagingSenderId: '123798050184',
    projectId: 'mealplanner-86fce',
    authDomain: 'mealplanner-86fce.firebaseapp.com',
    databaseURL: 'https://mealplanner-86fce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealplanner-86fce.appspot.com',
    measurementId: 'G-NGSPRG2VY5',
  );

}